### ISSUE TITLE
Caso de testes falhou - qtde de discos

### ISSUE THREAD

**Issue by dvriesman** [rafamilo/softplan-test#2]
mvn exec:java -Dexec.mainClass="com.rafamilo.App" -Dexec.args="100 90 50 30 30 10 50 8 85 6 95"

Está retornando 5 discos, mas o correto é 6 discos. 

exemplo: 
disco 01 =>  90 e 10
disco 02 => 50 e 30
disco 03 => 30 e 50
disco 04 => 8 e 85
disco 05 = 95
disco 06 = 6

**Comment by camilomelges** [comment]
Oi dvriesman, olhei seu caso de teste e realmente, esqueci-me que tem um limite de 2 arquivos por disco.

Subi um pr para resolver - https://github.com/rafamilo/softplan-test/pull/3

**Comment by rafamilo** [comment]
Subi um pr para resolver - https://github.com/rafamilo/softplan-test/pull/3
